name: Build Manjaro KDE Unstable ISO

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo pacman-mirrors --fasttrack && sudo pacman -Syy
          sudo pacman -S --needed --noconfirm manjaro-tools git p7zip

      - name: Prepare profile directory
        run: |
          mkdir -p ~/.config
          echo -e "[buildiso]\nprofile_dir = /home/runner/work/_temp/profile" > ~/.config/manjaro-tools.conf
          mkdir -p /home/runner/work/_temp/profile
          sudo cp -r /usr/share/manjaro-tools/buildiso/profiles/kde /home/runner/work/_temp/profile/kde
          sudo chown -R runner:runner /home/runner/work/_temp/profile

      - name: Patch profile for unstable branch
        run: |
          sed -i 's/^branch=.*/branch=unstable/' /home/runner/work/_temp/profile/kde/profile.conf

      - name: Build ISO
        run: |
          buildiso -p kde -b unstable -x

      - name: Compress ISO directory (limit <2GB)
        run: |
          mkdir -p release
          cp -v /var/cache/manjaro-tools/iso/unstable/*/*.iso release/
          cd release
          7z a manjaro-kde-unstable.zip *.iso

      - name: Upload ISO to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "unstable-kde-${{ github.run_number }}"
          name: "Manjaro KDE Unstable ${{ github.run_number }}"
          files: release/manjaro-kde-unstable.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
