name: Build Manjaro KDE Unstable

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/build:latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update system and install dependencies
      run: |
        pacman-mirrors -f 5
        pacman -Syu --noconfirm
        pacman -S --noconfirm manjaro-tools-iso-git git
        
    - name: Clone ISO profiles
      run: |
        git clone https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git /tmp/iso-profiles
        cp -r /tmp/iso-profiles/* /usr/share/manjaro-tools/iso-profiles/
        
    - name: Configure build environment
      run: |
        echo "PACKAGER='GitHub Actions <actions@github.com>'" >> /etc/makepkg.conf
        
    - name: List available profiles
      run: |
        ls -la /usr/share/manjaro-tools/iso-profiles/
        
    - name: Build Manjaro KDE Unstable ISO
      run: |
        buildiso -p kde -b unstable
        
    - name: List generated files
      run: |
        ls -la /var/cache/manjaro-tools/iso/
        
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: manjaro-kde-unstable-iso
        path: /var/cache/manjaro-tools/iso/*.iso
        retention-days: 7
        
    - name: Create release (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: /var/cache/manjaro-tools/iso/*.iso
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
