name: build_manjaro_kde_unstable

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: manjaro/manjaro-tools:latest
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (optional override)
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm git unzip p7zip

      - name: Configure build environment
        run: |
          mkdir -p ~/.config
          echo -e "[buildiso]\nprofile_dir = /profile" > ~/.config/manjaro-tools.conf

      - name: Copy KDE unstable profile
        run: |
          mkdir -p /profile
          cp -r /usr/share/manjaro-tools/buildiso/profiles/kde /profile/kde

      - name: Patch profile for unstable branch
        run: |
          sed -i 's@^branch=.*@branch=unstable@' /profile/kde/profile.conf

      - name: Build ISO (split mode)
        run: |
          buildiso -p kde -b unstable -x

      - name: Compress output files (<2GB ZIP)
        run: |
          mkdir -p release_files
          cp -a /var/cache/manjaro-tools/iso/unstable/*/*.iso ./release_files/
          cd release_files
          7z a manjaro-kde-unstable.zip *

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "unstable-kde-${{ github.run_number }}"
          name: "Manjaro KDE Unstable Build ${{ github.run_number }}"
          files: release_files/manjaro-kde-unstable.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
